JOB = [name:"TestJob26"/*, jobclass: Job class name here*/]
QUERY = '''testQueryNew'''
//QUERY_VARIABLE = // Variable to binding. 
//DBEXEC = /*fill DBEXEC here*/
//DBEXEC_VARIABLE = /*fill DBEXEC_VARIABLE here*/
COMMAND = '''testCommandNew'''
//FORMAT = /*fill FORMAT here*/
FETCHACTION = {
	testFetchactionNew
}
//ACCUMULATE = {
	/*code ACCUMULATE here*/
//}
//GROUPKEY = /*group key here*/
//FINALLY = {
	/*code FINALLY here*/
//}
//KEYEXPR = [:] /*Map config for KEYEXPR*/
//SENDTYPE = /*Config for SENDTYPE*/
//RESOURCEID = /*Config for RESOURCEID*/
//MONITORINGTYPE = /*Config for MONITORINGTYPE*/
//DBTYPE = /*Config for DBTYPE*/
DEST = parameters.dest
