JOB = [name:"TestJob20"/*, jobclass: Job class name here*/]
QUERY = '''testQuery'''
//QUERY_VARIABLE = // Variable to binding. 
DBEXEC = '''testDbexec'''
//DBEXEC_VARIABLE = /*fill DBEXEC_VARIABLE here*/
COMMAND = '''testCommand'''
//FORMAT = /*fill FORMAT here*/
FETCHACTION = {
	testFetchaction
}
//ACCUMULATE = {
	/*code ACCUMULATE here*/
//}
//GROUPKEY = /*group key here*/
//FINALLY = {
	/*code FINALLY here*/
//}
//KEYEXPR = [:] /*Map config for KEYEXPR*/
//SENDTYPE = /*Config for SENDTYPE*/
//RESOURCEID = /*Config for RESOURCEID*/
//MONITORINGTYPE = /*Config for MONITORINGTYPE*/
//DBTYPE = /*Config for DBTYPE*/
DEST = parameters.dest
